Added the frontend and backend regex modifications
jonathanhle/access pull request #1
Opened 2024-07-09 17:29 UTC by Jui1337

This change is for the Jira ticket - [PLATSEC-2944](https://gemini-spaceship.atlassian.net/browse/PLATSEC-2944).

2024-07-09 17:39 UTC, jonathanhle commented on .env.psql.example
> -#
@Jui1337 - this example file if from the Discord Dev team, so let's not delete it.

2024-07-09 17:49 UTC, sallyoswal reviewed
The Front End Changes are correct

2024-07-09 21:38 UTC, Jui1337 commented on .env.psql.example
> -#
Yes, I will add it back.

2024-07-10 17:36 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +import api.config
instead of importing the entire file can we just import the custom stuff we're defining?
e.g.

`from api.config import OKTA_APP_NAME_PATTERN`

Did you test to see if this works?

2024-07-10 17:37 UTC, jonathanhle commented on api/config.py
> +load_dotenv()
I'm not sure if:
`from dotenv import load_dotenv` or `load_dotenv()` is needed here.

We're using the `OKTA_DOMAIN = os.getenv("OKTA_DOMAIN")` already in the file and doesn't this already come from a loaded .env file?

2024-07-10 17:38 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                # "^[A-Z][A-Za-z0-9-]*$",
clean up commented pattern since we moved it to a default VAR

2024-07-10 17:39 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                error="App-backend-Group name must start capitalized and contain alphanumeric characters, underscores, @, periods, hyphens, backslash or *. "
Why add "App-backend-" here?

2024-07-10 17:42 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> -                error="Group name must start capitalized and contain only alphanumeric characters or hyphens. "
Going along with our ability to override the `OKTA_APP_NAME_PATTERN` now, I think we need to capture the default `error` message and be able to override this as well.  

E.g. if OKTA_APP_NAME_PATTERN exists but nothing is specified by custom config in .env, we should take the default Discord Access regex pattern and related error message.

If a custom is specified for OKTA_APP_NAME_PATTERN, we should also be able to specify a related custom error message.  I think this is the only way to stay consistent.

2024-07-10 17:44 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> -                error="Group name must start capitalized and contain only alphanumeric characters or hyphens. "
See comments about defaults and overrides for both the regex and error message string above.

2024-07-10 17:44 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                # "^[A-Z][A-Za-z0-9-]*$",
See similar comments above

2024-07-10 17:45 UTC, jonathanhle commented on src/index.tsx
> +console.log(`Environment variable: ${process.env.REACT_APP_OKTA_APP_NAME_PATTERN}`);
Okay for troubleshooting - probably should remove it though after.

2024-07-10 17:45 UTC, jonathanhle requested changes
@Jui1337 can you check on my comments and see if any of them make sense?

2024-07-10 17:46 UTC, jonathanhle commented
Overall good stuff so far, but let's so a bit more massaging on this.

2024-07-10 17:48 UTC, Jui1337 commented on api/views/schemas/core_schemas.py
> +import api.config
Yes, I tried it, but it was not working for me, I will test again before I push changes.

2024-07-10 17:54 UTC, Jui1337 commented on api/config.py
> +load_dotenv()
No, load_dotenv is how it loads the local env file. For me, the new variables were directly used with default values from config.py even if I specified their values in the ".env" file, with load_dotenv, it took the value from the env file. I can re-test before pushing again.

2024-07-10 17:54 UTC, Jui1337 commented on api/views/schemas/core_schemas.py
> +                # "^[A-Z][A-Za-z0-9-]*$",
My bad, I will remove all unnecessary comments and edit the "error" messages too.

2024-07-10 17:55 UTC, Jui1337 commented on api/views/schemas/core_schemas.py
> +                error="App-backend-Group name must start capitalized and contain alphanumeric characters, underscores, @, periods, hyphens, backslash or *. "
Apologies, I edited it for testing to see which script and function it threw me errors from, I will reset this!

2024-07-10 18:02 UTC, Jui1337 commented on api/views/schemas/core_schemas.py
> -                error="Group name must start capitalized and contain only alphanumeric characters or hyphens. "
Yes, gotcha, for the values, we do have default specified in config.py, so if nothing is declared in env, the default will be taken, but the error message for it is not handled, I will look for a logic to do this better.

2024-07-10 22:21 UTC, Jui1337 commented
@jonathanhle I made the reviewed changes, please let me know if I missed out on something!

2024-07-10 23:47 UTC, jonathanhle commented
Hi ! 
@Jui1337 there's really no rules to PR reviews, but I generally don't resolve comments until the issue raised is:
1) resolved
2) decided upon to work on later.  

 I think there's a couple of cases you are still going to handle. 
 
 When ready for me to review again click this button:
 
<img width="406" alt="image" src="https://github.com/jonathanhle/access/assets/3851599/a64e9335-c5f4-4f3a-bdfc-07a0bf08c039">

2024-07-11 20:46 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                error="App group name must start capitalized and contain characters allowed in the regex. "
Can we change "App group" back to "Group " here?

2024-07-11 20:48 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                error="App group name must start capitalized and contain characters allowed in the regex. "
Oh yeah - can we change "App group " here back to "Group ".

I have some reasons in that "App" in Discord Access mean something different than we do at Gemini and I don't want to explain it.

2024-07-11 20:48 UTC, jonathanhle commented on api/views/schemas/core_schemas.py
> +                error="App group name must start capitalized and contain characters allowed in the regex. "
Oh yeah - can we change "App group " here back to "Group ".

2024-07-11 20:49 UTC, jonathanhle requested changes
Super close - just two more comments

2024-07-11 23:20 UTC, Jui1337 commented
@jonathanhle ready to be merged, requesting for final review.

2024-07-15 18:39 UTC, jonathanhle approved these changes
LGTM!

2024-07-15 18:39 UTC, merged