FrontEnd Changes - #PlatSec - 2945
jonathanhle/access pull request #2
Opened 2024-07-09 21:24 UTC by sallyoswal

This change is for the Frontend...Regex that is updated for creating groups, apps and tags in discord access..in regard with this ticket 
 [PLATSEC-2945](https://gemini-spaceship.atlassian.net/browse/PLATSEC-2945)

2024-07-11 20:32 UTC, jonathanhle commented on src/RegexConfig.tsx
> +console.log(`Loaded REACT_APP_OKTA_APP_NAME_PATTERN: ${process.env.REACT_APP_OKTA_APP_NAME_PATTERN}`);
should we get rid of this `console.log`

2024-07-11 20:38 UTC, jonathanhle commented on src/pages/apps/CreateUpdate.tsx
> +                  return `Name must start capitalized and contain only alphanumeric characters or hyphens. Regex to match ${regexConfig.namePattern}`;
I don't know TSX really well at all.

Did you mean to change the
```
'
```
to
```
`
```

2024-07-11 20:40 UTC, jonathanhle commented on src/pages/apps/CreateUpdate.tsx
> +                  return `Name must start capitalized and contain only alphanumeric characters or hyphens. Regex to match ${regexConfig.namePattern}`;
Also with regard to `Name must start capitalized and contain only alphanumeric characters or hyphens` - we should seek to be accurate in this statement in the following cases:
1) No override for the pattern is given
2) An overrride for the pattern is given

This might mean that you also need to also this string to have a default value and an override value.

2024-07-11 20:41 UTC, jonathanhle commented
I left command on `src/pages/apps/CreateUpdate.tsx` but I think they apply to all the changes you did.  Can you review them?  

Going to request some changes.

2024-07-11 20:42 UTC, jonathanhle requested changes
See comments

2024-07-12 05:53 UTC, sallyoswal commented on src/pages/apps/CreateUpdate.tsx
> +                  return `Name must start capitalized and contain only alphanumeric characters or hyphens. Regex to match ${regexConfig.namePattern}`;
` is used instead of ' because backticks (`) allow us to embed variables directly.

2024-07-12 05:55 UTC, sallyoswal commented on src/RegexConfig.tsx
> +console.log(`Loaded REACT_APP_OKTA_APP_NAME_PATTERN: ${process.env.REACT_APP_OKTA_APP_NAME_PATTERN}`);
Done!

2024-07-15 18:59 UTC, jonathanhle approved these changes
LGTM

2024-07-15 19:00 UTC, merged